services:
  - type: web
    name: telebot-proxyless
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python trhiep.py"
    envVars:
      - key: BOT_TOKEN
        value: 7896551296:AAGVbUQpMzProDaMFg11M15vOVJRpP5w7JA
